export const IS_FETCHING = 'IS_FETCHING';

//Stat
export const GET_STAT_SUCCESS = 'GET_STAT_SUCCESS';
export const GET_STAT_FAILED = 'GET_STAT_FAILED';

//Setting
export const GET_SETTING_SUCCESS = 'GET_SETTING_SUCCESS';
export const GET_SETTING_FAILED = 'GET_SETTING_FAILED';
//Slice
export const GET_SLICES_SUCCESS = 'GET_SLICES_SUCCESS';
export const GET_SLICES_FAILED = 'GET_SLICES_FAILED';

//Update Wheel
export const IS_UPDATE_SETTING = 'IS_UPDATE_SETTING';
export const UPDATE_SETTING_SUCCESS = 'UPDATE_SETTING_SUCCESS';
export const UPDATE_SETTING_FAILED= 'UPDATE_SETTING_FAILED';

export const IS_UPDATE_SLICES = 'IS_UPDATE_SLICES';
export const UPDATE_SLICES_SUCCESS = 'UPDATE_SLICES_SUCCESS';
export const UPDATE_SLICES_FAILED = 'UPDATE_SLICES_FAILED';


//Mailchimp
export const GET_MAILCHIMP_SUCCESS = 'GET_MAILCHIMP_SUCCESS';
export const GET_MAILCHIMP_FAILED = 'GET_MAILCHIMP_FAILED';
export const IS_UPDATE_MAILCHIMP = 'IS_UPDATE_MAILCHIMP';
export const UPDATE_MAILCHIMP_SUCCESS = 'UPDATE_MAILCHIMP_SUCCESS';
export const UPDATE_MAILCHIMP_FAILED = 'UPDATE_MAILCHIMP_FAILED';
export const IS_CHECKING_MAILCHIMP = 'IS_CHECKING_MAILCHIMP';
export const CHECK_MAILCHIMP_CONNECT = 'CHECK_MAILCHIMP_CONNECT';

// export file excel
export const IS_EXPORT_FILE = 'IS_EXPORT_FILE';
export const EXPORT_FILE_SUCCESS = 'EXPORT_FILE_SUCCESS';
export const EXPORT_FILE_FAILED = 'EXPORT_FILE_FAILED';

//reset cookie user
export const IS_RESETTING_COOKIE = 'IS_RESETTING_COOKIE';
export const RESET_COOKIE = 'RESET_COOKIE';