export const IS_FETCHING = 'IS_FETCHING';
//Setting
export const GET_SETTING_SUCCESS = 'GET_SETTING_SUCCESS';
export const GET_SETTING_FAILED = 'GET_SETTING_FAILED';
//Slice
export const GET_SLICES_SUCCESS = 'GET_SLICES_SUCCESS';
export const GET_SLICES_FAILED = 'GET_SLICES_FAILED';

//Update Wheel
export const IS_UPDATE_SETTING = 'IS_UPDATE_SETTING';
export const UPDATE_SETTING_SUCCESS = 'UPDATE_SETTING_SUCCESS';
export const UPDATE_SETTING_FAILED= 'UPDATE_SETTING_FAILED';

export const IS_UPDATE_SLICES = 'IS_UPDATE_SLICES';
export const UPDATE_SLICES_SUCCESS = 'UPDATE_SLICES_SUCCESS';
export const UPDATE_SLICES_FAILED= 'UPDATE_SLICES_FAILED';

